language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env:
  matrix:
    - FLASK=0.10.1
    - FLASK=0.9
    - FLASK=0.8.1

matrix:
  include:
    - addons:
        mariadb: 5.5
    - addons:
        mariadb: 10.0
    - addons:
        mariadb: 10.1

services:
  - "redis"

install:
  - "pip install --upgrade pip"
  - "python -m pip install jsonschema"
  # add mariadb apt-get repository
  - "sudo apt-get install software-properties-common"
  - "sudo add-apt-repository 'deb http://ftp.kaist.ac.kr/mariadb/repo/5.5/ubuntu precise main'"
  # install mariadb server
  - "sudo apt-get update"
  - "sudo apt-get install python-mysqldb"
#  - "pip install -r requirements.txt"

# command to run tests
script:
  - nosetests
