language: python
dist: trusty
sudo: required

## configurations
##
## Note: riak needs to be removed:
##
##     - https://github.com/travis-ci/travis-ci/issues/8607
##
before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update
  - PROJECT_DIRECTORY=$(pwd)
  - chmod u+x test/linter
  - chmod u+x test/unit-tests

## install packages
install:
  - pip install python-coveralls==2.9.0
  - ./test/linter install

## lint and test
script:
  - ./test/linter run "$PROJECT_DIRECTORY"; LINT_EXIT=$?
  - ./test/unit-tests "$PROJECT_DIRECTORY"

## results: the following commands are run after linting, and tests have completed.
##
## Note: more information regarding the coverage-coverall implementation:
##
##       https://github.com/pytest-dev/pytest-cov/issues/146
##
after_success:
  - coverage combine
  - coveralls
  - if [ "$LINT_EXIT" -gt 0 ]; then exit 1; fi
