dist: trusty
sudo: required

##
## implement coveralls.io webhook
##
##     https://github.com/lemurheavy/coveralls-public/issues/1123#issuecomment-390699100
##     https://github.com/lemurheavy/coveralls-public/issues/1123#issuecomment-391030777
##
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN

matrix:
  include:
    - node_js: 8
      language: node_js
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

    - python: 3.4
      language: python

      ##
      ## environment variables
      ##
      ## @COVERALLS_PARALLEL, update coveralls only when branch merged
      ##
      env:
        - COVERALLS_PARALLEL=true

      ## configurations
      before_install:
      - chmod u+x test/linter
      - chmod u+x test/unit-tests

      ## install packages
      install:
      - pip install python-coveralls==2.9.0
      - ./test/linter install

      ## lint and test
      script:
      - ./test/linter run; LINT_EXIT=$?
      - ./test/unit-tests --norecycle --verbose; TEST_EXIT=$?

      ##
      ## results: the following commands are run after linting, and tests have completed.
      ##
      ## Note: more information regarding the coverage-coverall implementation:
      ##
      ##       https://github.com/pytest-dev/pytest-cov/issues/146
      ##
      after_success:
        - coverage combine
        - coveralls
        - if [ "$LINT_EXIT" -gt 0 ] && [ "$TEST_EXIT" -gt 0 ]; then echo "Lint ($LINT_EXIT) and Unit Tests failed" && exit 1; fi
        - if [ "$LINT_EXIT" -gt 0 ]; then echo "Lint Failed ($LINT_EXIT)" && exit 1; fi
        - if [ "$TEST_EXIT" -gt 0 ]; then echo 'Unit Tests Failed' && exit 1; fi
