sudo: required

language: python

## allows 'docker' command
services:
  - docker

## build docker container used for unit testing
before_install:
  - docker ps -a
  - docker build -t ubuntu/trusty .

## install packages for linting, and unit testing
install:
  - pip install flake8
  - npm install -g bootlint
  - npm install -g jshint
  - gem install scss_lint

## lint, and unit tests
#
#  @htmllint, the 'htmllint init' command will generate a configuration
#      file, '.htmllintrc' in the current directory.
script:
  - flake8 brain
  - flake8 web_interface
  - bootlint web_interface/templates/*.html
  - jshint --verbose src/js/*.js
  - scss-lint src/scss/*.scss --config test/linter/.scss-lint.yml
