sudo: required

language: python

## allows 'docker' command
services:
  - docker

## build docker container for unit testing.
before_install:
  - docker ps -a
  - docker build -t ubuntu/trusty .

## install packages for linting
#
#  Note: unit testing is performed within the docker container, which is
#        defined from the Dockerfile.
install:
  - pip install flake8
  - npm install -g jshint
  - npm install jscs -g
  - gem install scss_lint
  - npm install -g bootlint
  - gem install puppet-lint
  - gem install rubocop
  - npm install jsonlint -g
  - gem install csvlint
  - sudo apt-get update
  - sudo apt-get install libxml2-utils
  - gem install mdl

## implement linting
#
#  @puppet-lint, the following issue needs to be checked if it has been
#      resolved, so the '--no-ensure_first_param-check' abusive flag
#      implementation (below) can be removed:
#
#      - https://github.com/rodjek/puppet-lint/issues/410
#
#  Note: unit testing is performed within the docker container, which is
#        defined from the Dockerfile.
script:
  - flake8 .
  - jshint --verbose src/js/*.js --config test/config/jshint.json --exclude-path test/config/.jshintignore
  - jscs . --config test/config/.jscs.json
  - scss-lint src/scss/*.scss
  - bootlint interface/templates/*.html
  - puppet-lint --no-ensure_first_param-check puppet/manifests
  - rubocop puppet/Puppetfile --except Style/HashSyntax
  - rubocop puppet/scripts/Puppetfile --except Style/HashSyntax
  - find interface/static/data/json -name '*.json' -exec jsonlint -q {} \; -print
  - find interface/static/data/csv -name '*.csv' -exec csvlint {} \;
  - xmllint --valid --noout interface/static/data/xml/*.xml
  - mdl .
