language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
services:
  - "redis"
env:
  - "FLASK=0.10.1"
  - "FLASK=0.9"
  - "FLASK=0.8.1"
install:
  - "python -m pip install Flask==$FLASK"
  - "python -m pip install jsonschema"
  - "sudo apt-get install mariadb-server mariadb-client python-mysqldb"
#  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
