language: python
dist: trusty
sudo: required

## configurations
before_install:
  - PROJECT_DIRECTORY=$(pwd)
  - chmod u+x test/linter
  - chmod u+x test/unit-tests

## install packages
##
## @trusty-backports, allows additional packages (i.e. shellcheck) to be installed
##
install:
  - wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
  - sudo dpkg -i puppetlabs-release-pc1-trusty.deb
  - sudo apt-get update
  - sudo apt-get install puppet-agent -y
  - sudo /opt/puppetlabs/bin/puppet -V
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - pip install python-coveralls==2.9.0
  - ./test/linter install

## lint and test
script:
  - ./linter run "$PROJECT_DIRECTORY"
  - ./unit-tests "$PROJECT_DIRECTORY"

## results: the following commands are run after linting, and tests have completed.
##
## Note: more information regarding the coverage-coverall implementation:
##
##       https://github.com/pytest-dev/pytest-cov/issues/146
##
after_success:
  - coverage combine
  - coveralls
