language: python
python:
  - "2.7"

sudo: required

services:
  - docker
  - redis

env:
  - FLASK=0.10.1

addons:
  mariadb: "10.0"

install:
  - sudo apt-get update
  - pip install --upgrade pip
  - pip install Flask==$FLASK
  - pip install jsonschema
  - sudo apt-get install python-mysql.connector
  - sudo apt-get install python-mysqldb
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

# command to run tests
before_script:
  - docker pull ubuntu:14.04
script:
  - docker-compose up
  - nosetests
