language: python
python:
  - "3.3"
  - "2.7"

env:
  - FLASK=0.10.1

matrix:
  include:
    - addons:
        mariadb: 5.5
      env:
        - FLASK=0.10.1
    - addons:
        mariadb: 10.0
      env:
        - FLASK=0.10.1
    - addons:
        mariadb: 10.1
      env:
        - FLASK=0.10.1

services:
  - "redis"

install:
  - pip install Flask==$FLASK
  - pip install --upgrade pip
  - pip install jsonschema
  # add mariadb apt-get repository
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository 'deb http://ftp.kaist.ac.kr/mariadb/repo/5.5/ubuntu precise main'
  # install mariadb server
  - sudo apt-get update
  - sudo apt-get install python-mysqldb
#  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests
