sudo: required

language: python

## allows 'docker' command
services:
  - docker

## setup ssh keypair, build docker container
before_install:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "$travis_pull_private_key" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval `ssh-agent -s`
  - ssh -vT git@github.com
  - docker build -t ubuntu/trusty .
  - docker ps -a

## install packages for linting, and unit testing
install:
  - pip install flake8

## lint, and unit tests
script:
  - flake8 brain
  - flake8 web_interface
