language: python
python:
  - "2.7"

env:
  - FLASK=0.10.1

addons:
  mariadb: "10.0"

services:
  - "redis"

install:
  - pip install --upgrade pip
  - pip install Flask==$FLASK
  - pip install jsonschema
  # install python-mysqldb dependencies
  - sudo apt-get install libmysqlclient18
  - sudo apt-get install python-dev libmysqlclient-dev
  # install python mysql connector
  - pip install MYSQL-python
#  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests
