sudo: required

language: python

## allows 'docker' command
services:
  - docker

before_install:  
  - docker build -t ubuntu/trusty .
  - docker ps -a

install:
  - pip install flake8

## run tests
script:
  - flake8 brain
  - flake8 web_interface
