sudo: required

language: python

## allows 'docker' command
services:
  - docker

## build docker, install puppet (i.e. puppet parser validate)
before_install:
  - docker build -t ubuntu/trusty .
  - docker run ubuntu/trusty bash -c "/opt/puppetlabs/bin/puppet apply /var/machine-learning/puppet/environment/development/manifests/configure_redis.pp --modulepath=/var/machine-learning/puppet/environment/development/modules_contrib:/var/machine-learning/puppet/environment/development/modules --confdir=/var/machine-learning/test"
  - docker run ubuntu/trusty bash -c "/opt/puppetlabs/bin/puppet apply /var/machine-learning/puppet/environment/development/manifests/setup_database.pp --modulepath=/var/machine-learning/puppet/environment/development/modules_contrib:/var/machine-learning/puppet/environment/development/modules --confdir=/var/machine-learning/test"
  - docker run ubuntu/trusty bash -c "/opt/puppetlabs/bin/puppet apply /var/machine-learning/puppet/environment/development/manifests/start_webserver.pp --modulepath=/var/machine-learning/puppet/environment/development/modules_contrib:/var/machine-learning/puppet/environment/development/modules --confdir=/var/machine-learning/test"
  - wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
  - sudo dpkg -i puppetlabs-release-pc1-trusty.deb
  - sudo apt-get update
  - sudo apt-get install puppet-agent -y
  - ls -l /opt/puppetlabs/bin

## install packages for linting
#
#  @trusty-backports, allows additional packages (i.e. shellcheck) to be installed
#
#  Note: unit testing is performed within the docker container, which is
#        defined from the Dockerfile.
install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - pip install flake8==2.5.4
  - npm install -g jshint@2.9.1
  - npm install -g jscs@2.11.0
  - gem install scss_lint -v 0.38.0
  - npm install -g bootlint@0.14.2
  - gem install puppet-lint -v 1.1.0
  - gem install r10k -v 2.2.0
  - npm install -g jsonlint@1.6.2
  - gem install csvlint -v 0.3.0
  - sudo apt-get update
  - sudo apt-get install libxml2-utils=2.9.1+dfsg1-3ubuntu4.8
  - gem install mdl -v 0.3.1
  - sudo apt-get install shellcheck=0.3.3-1~ubuntu14.04.1
  - npm install -g eslint babel-eslint@6.0.0-beta.6
  - npm install -g eslint-plugin-react@4.2.3
  - gem install yaml-lint -v 0.0.7
  - npm install -g travis-lint@1.0.0

## implement linting
#
#  @puppet-lint, the following issue needs to be checked if it has been
#      resolved, so the '--no-ensure_first_param-check' abusive flag
#      implementation (below) can be removed:
#
#      - https://github.com/rodjek/puppet-lint/issues/410
#
#  @docker run:
#      -d, run container in background and print container ID
#
#  Note: unit testing is performed within the docker container, which is
#        defined from the Dockerfile.
script:
  - flake8 .
  - jshint --verbose src/js/*.js --config test/config/jshint.json --exclude-path test/config/.jshintignore
  - jscs . --config test/config/.jscs.json
  - scss-lint src/scss/*.scss
  - bootlint -d W005 interface/templates/*.html
  - find puppet/environment/development/manifests -name '*.pp' -type f -exec /opt/puppetlabs/bin/puppet parser validate {} \;
  - find puppet/environment/development/modules -name '*.pp' -type f -exec /opt/puppetlabs/bin/puppet parser validate {} \;
  - puppet-lint --no-variable_scope-check --no-ensure_first_param-check puppet/environment/development/modules
  - (cd puppet/environment/development/ && r10k puppetfile check)
  - (cd test/ && r10k puppetfile check)
  - find interface/static/data/json -name '*.json' -exec jsonlint -q {} \; -print
  - find interface/static/data/csv -name '*.csv' -exec csvlint {} \;
  - xmllint --noout interface/static/data/xml/svr*.xml --schema interface/static/data/xml/svr.xsd
  - xmllint --noout interface/static/data/xml/svm*.xml --schema interface/static/data/xml/svm.xsd
  - xmllint --noout interface/static/data/xml/*.xsd
  - mdl . --style test/config/markdown.rb
  - find . -type f -exec grep -l '^#!/bin/bash' {} + | xargs shellcheck
  - find . -name '*.sh' -type f -exec shellcheck {} \;
  - eslint . --ext=jsx -c test/config/eslint.json
  - yaml-lint hiera/
  - yaml-lint *.yaml
  - travis-lint .travis.yml
  - docker run ubuntu/trusty bash -c "cd /var/machine-learning/test; py.test"
