language: python
dist: trusty
sudo: required

## configurations
before_install:
  - PROJECT_DIRECTORY=$(pwd)
  - chmod u+x test/linter
  - chmod u+x test/unit-tests

## install packages
install:
  - pip install python-coveralls==2.9.0
  - ./test/linter install

## lint and test
script:
  - ./test/linter run "$PROJECT_DIRECTORY"; LINT_EXIT=$?
  - ./test/unit-tests "$PROJECT_DIRECTORY"; TEST_EXIT=$?

## results: the following commands are run after linting, and tests have completed.
##
## Note: more information regarding the coverage-coverall implementation:
##
##       https://github.com/pytest-dev/pytest-cov/issues/146
##
after_success:
  - coverage combine
  - coveralls
  - if [ "$LINT_EXIT" -gt 0 ] && [ "$TEST_EXIT" -gt 0 ]; then echo "Lint ($LINT_EXIT) and Unit tests Failed" && exit 1; fi
  - if [ "$LINT_EXIT" -gt 0 ]; then echo "Lint Failed ($LINT_EXIT)" && exit 1; fi
  - if [ "$TEST_EXIT" -gt 0 ]; then echo 'Unit tests Failed' && exit 1; fi
