language: python
dist: trusty
sudo: required

## configurations
before_install:
  - PROJECT_DIRECTORY=$(pwd)
  - chmod u+x test/linter
  - chmod u+x test/unit-tests

## install packages
install:
  - pip install python-coveralls==2.9.0
  - ./test/linter install

## lint and test
script:
  - ./test/linter run "$PROJECT_DIRECTORY"
  - ./test/unit-tests "$PROJECT_DIRECTORY"

## results: the following commands are run after linting, and tests have completed.
##
## Note: more information regarding the coverage-coverall implementation:
##
##       https://github.com/pytest-dev/pytest-cov/issues/146
##
after_success:
  - coverage combine
  - coveralls
