sudo: required

language: python

## allows 'docker' command
services:
  - docker

## build docker container used for unit testing
before_install:
  - docker ps -a
  - docker build -t ubuntu/trusty .

## install packages for linting, and unit testing
install:
  - pip install flake8
  - npm install -g jshint
  - gem install scss_lint
  - npm install -g bootlint
  - gem install puppet-lint
  - gem install rubocop
  - npm install jsonlint -g
  - gem install csvlint
  - sudo apt-get install libxml2-utils

## lint, and unit tests
script:
  - flake8 brain
  - flake8 interface
  - jshint --verbose src/js/*.js
  - scss-lint src/scss/*.scss
  - bootlint interface/templates/*.html
  - puppet-lint puppet/manifests
  - rubocop puppet/Puppefile
  - rubocop puppet/scripts/Puppetfile
  - find interface/static/data/json -name '*.json' -exec jsonlint -q {} \; -print
  - find interface/static/data/csv -name '*.csv' -exec csvlint {} \;
  - xmllint --valid --noout interface/static/data/xml/*.xml