sudo: required

language: ruby

# allows 'docker' command
services:
  - docker

before_install:  
  - docker build -t ubuntu/trusty .
  - docker ps -a

# command to run tests
#  - bundle exec rake test
