language: python
python:
  - "2.7"

env:
  - FLASK=0.10.1

addons:
  mariadb: "10.0"

services:
  - "redis"

install:
  - sudo apt-get update
  - pip install --upgrade pip
  - pip install Flask==$FLASK
  - pip install jsonschema
  - sudo apt-get install python-mysql.connector
  - sudo apt-get install python-mysqldb
#  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests
