language: python
python:
  - "2.7"

env:
  - FLASK=0.10.1

addons:
  mariadb: "10.0"

services:
  - "redis"

install:
  - sudo apt-get update
  - pip install --upgrade pip
  - pip install Flask==$FLASK
  - pip install jsonschema
  # install python-mysqldb dependencies
  - gpg --keyserver  hkp://keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
  - gpg -a --export CD2EFD2A | apt-key add -
  - sudo sh -c 'echo "deb http://repo.percona.com/apt precise main" >> /etc/apt/sources.list.d/percona.list'
  - sudo apt-get update
  - sudo apt-get install python-dev libmysqlclient-dev
  # install python-mysqldb connector
  - pip install MYSQL-python
#  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests
