version: '2'
services:
  mariadb:
    hostname: mariadb
    image: jeff1evesque/ml-mariadb:0.7
    command: >
        /bin/bash -c
        'cd /etc/puppetlabs/code/modules/mariadb/scripts
        && python setup_tables.py /etc/puppetlabs/puppet'
    network_mode: bridge

  mongodb:
    hostname: mongodb
    image: jeff1evesque/ml-mongodb:0.7
    command: >
        /bin/bash -c
        '/usr/bin/mongod --fork --config /etc/mongod.conf
        && cd /root/build
        && ./create-mongodb-users'
    network_mode: bridge

  redis:
    hostname: redis
    image: jeff1evesque/ml-redis:0.7
    network_mode: bridge

  browserify:
    hostname: browserify
    image: jeff1evesque/ml-browserify:0.7
    network_mode: bridge

  sass:
    hostname: sass
    image: jeff1evesque/ml-sass:0.7
    command: /bin/bash -c 'touch /var/machine-learning/src/scss/style.scss'
    network_mode: bridge

  webserver-api:
    hostname: webserver-api
    image: jeff1evesque/ml-webserver:0.7
    command: ['0.0.0.0', '6001', '6', 'api']
    network_mode: bridge
    ports:
    - 6000:9090/tcp

  webserver-web:
    hostname: webserver-web
    image: jeff1evesque/ml-webserver:0.7
    command: ['0.0.0.0', '5001', '6', 'web']
    network_mode: bridge
    ports:
    - 5000:8080/tcp

  nginx-api:
    hostname: nginx-api
    image: jeff1evesque/ml-nginx-api:0.7
    network_mode: bridge

  nginx-web:
    hostname: nginx-web
    image: jeff1evesque/ml-nginx-web:0.7
    network_mode: bridge
