version: '2'
services:
  mariadb:
    hostname: mariadb
    image: jeff1evesque/ml-mariadb:0.7
    network_mode: bridge

  mongodb:
    hostname: mongodb
    image: jeff1evesque/ml-mongodb:0.7
    network_mode: bridge

  redis:
    hostname: redis
    image: jeff1evesque/ml-redis:0.7
    network_mode: bridge

  browserify:
    hostname: browserify
    image: jeff1evesque/ml-browserify:0.7
    network_mode: bridge

  sass:
    hostname: sass
    image: jeff1evesque/ml-sass:0.7
    network_mode: bridge

  webserver_api:
    hostname: webserver_api
    image: jeff1evesque/ml-webserver:0.7
    command: ['api', '0.0.0.0', '6001', '6']
    network_mode: bridge

  webserver_web:
    hostname: webserver_web
    image: jeff1evesque/ml-webserver:0.7
    command: ['web', '0.0.0.0', '5001', '6']
    network_mode: bridge

  nginx_api:
    hostname: nginx_api
    image: jeff1evesque/ml-nginx-api:0.7
    network_mode: bridge
    ports:
    - 9090:6000/tcp

  nginx_web:
    hostname: nginx_web
    image: jeff1evesque/ml-nginx-web:0.7
    network_mode: bridge
    ports:
    - 8080:5000/tcp
