version: '2'
services:
  mariadb:
    hostname: mariadb
    image: jeff1evesque/ml-mariadb:0.7
    network_mode: bridge
  webserver:
    hostname: webserver
    image: jeff1evesque/ml-webserver:0.7
    network_mode: bridge
    ports:
    - 5000:8080/tcp
    - 6000:9090/tcp
  nginx-api:
    hostname: nginx-api
    image: jeff1evesque/ml-nginx:0.7
    network_mode: bridge
  nginx-web:
    hostname: nginx-web
    image: jeff1evesque/ml-nginx:0.7
    network_mode: bridge
  mongodb:
    hostname: mongodb
    image: jeff1evesque/ml-mongodb:0.7
    network_mode: bridge
  redis:
    hostname: redis
    image: jeff1evesque/ml-redis:0.7
    network_mode: bridge
  base:
    hostname: base
    image: jeff1evesque/ml-base:0.7
    network_mode: bridge
