version: '2'
services:
  mariadb:
    image: jeff1evesque/ml-mariadb:0.7
    network_mode: bridge
    volumes:
    - docker_storage_mariadb:/var/lib/mariadb
  webserver:
    image: jeff1evesque/ml-webserver:0.7
    network_mode: bridge
    ports:
    - 5000:8080/tcp
    - 6000:9090/tcp
  mongodb:
    image: jeff1evesque/ml-mongodb:0.7
    network_mode: bridge
    volumes:
    - docker_storage_mongodb:/var/lib/mongodb
  redis:
    image: jeff1evesque/ml-redis:0.7
    network_mode: bridge
    volumes:
    - docker_storage_redis:/var/lib/redis
  base:
    image: jeff1evesque/ml-base:0.7
    network_mode: bridge
