version: '2'
services:
  base:
    image: jeff1evesque/ml-default
    container_name: base
    network_mode: bridge

  redis:
    image: jeff1evesque/ml-redis
    container_name: redis
    network_mode: bridge
    volumes:
      - ./docker_storage_redis:/var/lib/redis

  mongodb:
    image: jeff1evesque/ml-mongodb
    container_name: mongodb
    network_mode: bridge
    volumes:
      - ./docker_storage_mongodb:/var/lib/mongodb

  mariadb:
    image: jeff1evesque/ml-mariadb
    container_name: mariadb
    network_mode: bridge
    volumes:
      - ./docker_storage_mariadb:/var/lib/mariadb

  webserver:
    image: jeff1evesque/ml-webserver
    container_name: webserver
    network_mode: bridge
    ports:
      - 5000:8080
      - 6000:9090
