version: '2'
services:
  mariadb:
    hostname: mariadb
    image: jeff1evesque/ml-mariadb:0.7
    network_mode: bridge
  webserver-api:
    hostname: webserver-api
    image: jeff1evesque/ml-webserver0.7
    network_mode: bridge
    volumes:
        - ${PWD}/log:/var/machine-learning/log
        - ${PWD}/interface:/var/machine-learning/interface/__init__
        - ${PWD}/interface:/var/machine-learning/interface/views_api.py
        - ${PWD}/hiera:/var/machine-learning/hiera
        - ${PWD}/brain:/var/machine-learning/brain
        - ${PWD}/test:/var/machine-learning/test
        - ${PWD}/app.py:/var/machine-learning/app.py
        - ${PWD}/factory.py:/var/machine-learning/factory.py
        - ${PWD}/__init__.py:/var/machine-learning/__init__.py
    ports:
    - 6000:9090/tcp
  webserver-web:
    hostname: webserver-web
    image: jeff1evesque/ml-webserver:0.7
    network_mode: bridge
    volumes:
        - ${PWD}/log:/var/machine-learning/log
        - ${PWD}/interface:/var/machine-learning/interface/__init__
        - ${PWD}/interface:/var/machine-learning/interface/views_web.py
        - ${PWD}/interface:/var/machine-learning/interface/templates
        - ${PWD}/hiera:/var/machine-learning/hiera
        - ${PWD}/brain:/var/machine-learning/brain
        - ${PWD}/test:/var/machine-learning/test
        - ${PWD}/app.py:/var/machine-learning/app.py
        - ${PWD}/factory.py:/var/machine-learning/factory.py
    ports:
    - 5000:8080/tcp
  nginx-api:
    hostname: nginx-api
    image: jeff1evesque/ml-nginx-api:0.7
    network_mode: bridge
  nginx-web:
    hostname: nginx-web
    image: jeff1evesque/ml-nginx-web:0.7
    network_mode: bridge
  mongodb:
    hostname: mongodb
    image: jeff1evesque/ml-mongodb:0.7
    network_mode: bridge
  redis:
    hostname: redis
    image: jeff1evesque/ml-redis:0.7
    network_mode: bridge
  browserify:
    hostname: browserify
    image: jeff1evesque/ml-browserify:0.7
    network_mode: bridge
    volumes:
        - ${PWD}/src/jsx:/var/machine-learning/src/jsx
        - ${PWD}/src/js:/var/machine-learning/src/js
        - ${PWD}/interface/static/js:/var/machine-learning/interface/static/js
  sass:
    hostname: sass
    image: jeff1evesque/ml-sass:0.7
    network_mode: bridge
    volumes:
        - ${PWD}/src/scss:/var/machine-learning/src/scss
        - ${PWD}/interface/static/css:/var/machine-learning/interface/static/css
