version: '3'
services:
  default:
    container_name: 'default'
    dockerfile: default.dockerfile
    network_mode: bridge

  redis:
    container_name: 'redis'
    dockerfile: redis.dockerfile
    network_mode: bridge
    volumes:
      - ./docker_storage_redis: /var/lib/redis

  mongodb:
    container_name: 'mongodb'
    dockerfile: mongodb.dockerfile
    network_mode: bridge
    volumes:
      - ./docker_storage_mongodb: /var/lib/mongodb

  mariadb:
    container_name: 'mariadb'
    dockerfile: mariadb.dockerfile
    network_mode: bridge
    volumes:
      - ./docker_storage_mariadb: /var/lib/mariadb

  webserver:
    container_name: 'webserver'
    dockerfile: webserver.dockerfile
    network_mode: bridge
    ports:
      - '5000:8080'
      - '6000:9090'
