version: '2'
services:
  mariadb:
    scale: 1
    start_on_create: true
  webserver:
    scale: 1
    start_on_create: true
  nginx-api:
    scale: 1
    start_on_create: true
  nginx-web:
    scale: 1
    start_on_create: true
  mongodb:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
