##
## This file contains database related configurations:
##
##  - mongodb
##  - mariadb
##
database:
    mariadb:
        host: 'localhost'
        name: 'db_machine_learning'
        provisioner: 'provisioner'
        provisioner_password: 'password'
        username: 'authenticated'
        password: 'password'
        tester: 'tester'
        tester_password: 'password'
        root_password: 'password'
        log_path: '/log/database'

    mongodb:
        hostname: 'localhost'
        name: 'dataset'
        username: 'authenticated'
        password: 'password'

        storage:
            dbPath:
                - '/data'
                - '/data/db'
            journal:
                enabled: true

        systemLog:
            verbosity: 1
            destination: file
            logAppend: true
            systemLogPath: '/var/log/mongodb/mongod.log'

        net:
            port: 27017
            bindIp: 127.0.0.1

        processManagement:
            fork: true
            pidfilepath: '/var/run/mongod.pid'
